### PR TITLE
Adds fan-light driver and device

### PR DESCRIPTION
**Pull request by gslender**
Adds Adds fan-light driver and device but requires a rethink on how to accomodate the needed additional capabilities (of which I just borrowed from volume_mute and volume_set (where I believe you could easily create fan_onoff and fan_set along with the needed single UI to manage the on/off and speed setting in one panel).

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Thanks for the PR!

Why did you choose to use `volume_` capabilities? It would be much better to use `onoff.fan` and `dim.fan`.

Also, the class is `fan`, but the capabilities imply the main class is a `light`. Is this on purpose?

**Comment by gslender** [comment]
I wasn't sure what the UI would end up being with `onoff.fan` as remember I don't have a device to test against. I wanted the UI to create another panel. As for the main device class, that's up for debate as the MAIN purpose of the device is a fan, it just happens to have a light as a secondary feature (not the primary purpose).

**Comment by WeeJeWel** [comment]
Using sub-capabilities would create a dropdown in the 'On/Off' panel.

If the main class is a fan, shouldn't we re-use the `fan` driver and dynamically add these light capabilities then?

**Comment by gslender** [comment]
I think the entire fan light combo needs thought and attention

**Comment by gslender** [comment]
>If the main class is a fan, shouldn't we re-use the fan driver and dynamically add these light capabilities then?

Nope, because you are checking the device status for features, and my fan (which definitely doesn't have a light) just reports the status of the light as false/off, so just because the status of the light is off doesn't mean you don't have one. 

I might be wrong, but I think you probably need to talk to the Tuya API folks and ask them how you figure out what features the device has, because some Tuya devices don't have the feature but report the status of the feature as off/false which clearly that's true (a missing light's status is off/false) but that doesn't mean you have a light. So a separate fan-light device seemed like the best way to be confident that indeed the status' are what they are mean't to be

**Comment by gslender** [comment]
>Using sub-capabilities would create a dropdown in the 'On/Off' panel.

I'll look into that, but personally I'm not a fan of the sub-capabilities and dropdown as the UI... its ugly and hard to use for quick changes. Not my fav way to control a fan-light combo device (which I do have on a zigbee device but not on one of these Tuya Cloud devices)

**Comment by gslender** [comment]
@WeeJeWel any thoughts regarding my comments? If the PR won't be accepted, happy for you to just close with a comment saying so - I didn't really expect this addition of a combo fan-light to be easy to add considering your Homey ecosystem doesn't really consider a fan device fully/correctly either. Another possible approach would be to create my own custom fan capabiliites, but is that where you wish this to go? Happy to do that if you feel that's a better option.

**Comment by gslender** [comment]
@WeeJeWel any update ??

**Comment by gslender** [comment]
Have put the icon ceiling fan back to replace the incorrect (IMO) desk fan device

**Comment by bobvandevijver** [comment]
@gslender Thank your for the PR! Looks like the combined fan/light uses the same device type as a normal fan, so my preference would be to combine it with the existing fan driver. We have made quite some changes to the light class, and we will have to think how we are going to do that. I'm pretty sure that the code in this PR isn't how we want to solve it, so chances are that I am going to close it in a couple of weeks. Obviously we will keep you updated, and if you have any further suggestions just post them in #8!

**Comment by gslender** [comment]
That approach won't be ideal - there is no way to know if the Tuya device truly has light capabilities (as they all do from the Tuya software side, but not so in the physical hardware device), so you'll be adding light feature to EVERY fan when they don't have one. Users will hate this and complain. Please read this PR thread again carefully. https://github.com/athombv/com.tuya/pull/27#issuecomment-2186392075

**Pull request closed without merging**
