### PR TITLE
functon which can redact device log fields

### PR DESCRIPTION
**Pull request by eelco2k**

### CODE REVIEW

**Review by bobvandevijver — CHANGES_REQUESTED** [review]
Thank you for the PR!  It is actually less important in the log (which should remain local as we no longer request people to use the CLI to create their requests), but it does need to be sanitized in the `other` driver where the settings are generated:

https://github.com/athombv/com.tuya/blob/5767e19126ae07ad70b5cb6a0e555af40ef8a595/drivers/other/driver.js#L18

Can you add it there as well, and lets add the following field as well. For my part you can make this the default list for the function, so we do not need to pass the same list twice.

- `local_key`

**Comment by eelco2k** [comment]
added your requests. But i did not use it as default list but as these fields always need to be redacted i combine the list with the incoming array of second param of the redactFields function. that way you cannot override and miss the ip,lat,lon etc. fields

**Review by bobvandevijver — APPROVED** [review]

**Comment by bobvandevijver** [comment]
Many thanks @eelco2k! I did find a small bug, but fixed that. Will be pushing a release with this soon.

**Comment by eelco2k** [comment]
perfect! I did not test the code so good you found that bugger 👍

**Comment by eelco2k** [comment]
does the line : 
`this.log('Device:', JSON.stringify(TuyaOAuth2Util.redactFields(device)));`
not be:
`this.log('Device:', JSON.stringify(TuyaOAuth2Util.redactFields(device.device)));`

i'm not completely sure...? as the json has 2 keys, "device" and "specifications" ...

**Comment by bobvandevijver** [comment]
No, that was actually the source of the bug. The JSON with two keys is returned by Tuya, but constructed by us in the `other` driver.

**Comment by eelco2k** [comment]
yes i understand, on the driver.js i understand, but i mean in the [lib/TuyaOAuth2Driver.js] file in the onPairListDevices() function.  is it there also correct? if so. i have said nothing.. :)

**Comment by bobvandevijver** [comment]
The `TuyaOAuth2Driver.js` `onPairListDevices` function does not yet have the specification part (that is line 23), so yes, it is correct as it is now 👍🏻

**Pull request merged**
